# Makefile for "Wayne's Little DSA Library"
# (DSA == Data Structures and Algorithms)
# Feel free to change, modify, or burn these sources, but if you modify them
# please don't distribute your changes without a clear indication that you've done so.
# If you think your change is spiffy, send it to me and maybe I'll include it
# 
# Wayne Hayes, wayne@csri.utoronto.ca (preffered), or wayne@csri.toronto.edu
CC=../bin/wgcc

#% : %.c
#	$(CC) -c $(CFLAGS) %.c
#	wf77 -o % %.o


OBJS=aloha.o bintree-test.o combin.o graph-sanity.o integrate-friction.o integrator-order.o integrators.o linked-list-test.o normStat.o queue.o revlines.o sparse-set-sanity.o set-sanity.o stats.o stream48.o test_SSetDict.o test_llfile.o uncmind.o x_mouse.o x_random.o

