#!/bin/sh
# Whatever you use to run things in parallel.
P="parallel 64"

SIFT=../canon-sift # the executable used to do the sifting.
TMP=/tmp/sift8 # You should create this directory manually and remove it when done
# Note: the set of *all* commands generated by each line of awk must finished before the next set starts.
awk 'BEGIN{for(i=0;i<256;i++)printf "'$SIFT' 8 8.%03d 8.%03d > '$TMP'/8.1.%03d\n",2*i,2*i+1,i;exit}'|parallel 64
awk 'BEGIN{for(i=0;i<128;i++)printf "'$SIFT' 8 '$TMP'/8.1.%03d '$TMP'/8.1.%03d > '$TMP'/8.2.%03d\n",2*i,2*i+1,i;exit}' | $P
awk 'BEGIN{for(i=0;i<64;i++)printf "'$SIFT' 8 '$TMP'/8.2.%03d '$TMP'/8.2.%03d > '$TMP'/8.3.%03d\n",2*i,2*i+1,i;exit}' | $P
awk 'BEGIN{for(i=0;i<32;i++)printf "'$SIFT' 8 '$TMP'/8.3.%03d '$TMP'/8.3.%03d > '$TMP'/8.4.%03d\n",2*i,2*i+1,i;exit}' | $P
awk 'BEGIN{for(i=0;i<16;i++)printf "'$SIFT' 8 '$TMP'/8.4.%03d '$TMP'/8.4.%03d > '$TMP'/8.5.%03d\n",2*i,2*i+1,i;exit}' | $P
awk 'BEGIN{for(i=0;i<8;i++)printf "'$SIFT' 8 '$TMP'/8.5.%03d '$TMP'/8.5.%03d > '$TMP'/8.6.%03d\n",2*i,2*i+1,i;exit}' | $P
awk 'BEGIN{for(i=0;i<4;i++)printf "'$SIFT' 8 '$TMP'/8.6.%03d '$TMP'/8.6.%03d > '$TMP'/8.7.%03d\n",2*i,2*i+1,i;exit}' | $P
awk 'BEGIN{for(i=0;i<2;i++)printf "'$SIFT' 8 '$TMP'/8.7.%03d '$TMP'/8.7.%03d > '$TMP'/8.8.%03d\n",2*i,2*i+1,i;exit}' | $P
awk 'BEGIN{for(i=0;i<1;i++)printf "'$SIFT' 8 '$TMP'/8.8.%03d '$TMP'/8.8.%03d > 8.9.%03d\n",2*i,2*i+1,i;exit}' | $P
